/**
 * Stellar DataStore
 * The Stellar DataStore service is your instantly available, secure and worry-free cloud data storage service. Sign-up now and minutes later, you can start putting your data in the cloud.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Stream {
    'canRead'?: boolean;
    'canWrite'?: boolean;
    'canSeek'?: boolean;
    'canTimeout'?: boolean;
    'length'?: number;
    'position'?: number;
    'readTimeout'?: number;
    'writeTimeout'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "canRead",
            "baseName": "canRead",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canWrite",
            "baseName": "canWrite",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canSeek",
            "baseName": "canSeek",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canTimeout",
            "baseName": "canTimeout",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "readTimeout",
            "baseName": "readTimeout",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "writeTimeout",
            "baseName": "writeTimeout",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return Stream.attributeTypeMap;
    }

    public constructor() {
    }
}
